const PizZip = require('pizzip');
const Docxtemplater = require('docxtemplater');
const fs = require('fs');
const path = require('path');

// This creates a minimal valid .docx file with placeholder content
// You can open these in Word and customize them further

const createMinimalDocx = (content) => {
  // Minimal Word document XML structure
  const documentXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:body>
    ${content}
  </w:body>
</w:document>`;

  const contentTypesXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
</Types>`;

  const relsXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
</Relationships>`;

  const zip = new PizZip();
  zip.file('word/document.xml', documentXml);
  zip.file('[Content_Types].xml', contentTypesXml);
  zip.file('_rels/.rels', relsXml);
  
  return zip.generate({ type: 'nodebuffer' });
};

const p = (text, bold = false) => {
  if (bold) {
    return `<w:p><w:r><w:rPr><w:b/></w:rPr><w:t>${text}</w:t></w:r></w:p>`;
  }
  return `<w:p><w:r><w:t xml:space="preserve">${text}</w:t></w:r></w:p>`;
};

const br = () => '<w:p/>';

// Inventory Report Template
const inventoryReportContent = [
  p('INVENTORY REPORT', true),
  p('Generated on: {reportDate}'),
  p('By: {generatedBy}'),
  br(),
  p('SUMMARY', true),
  p('Total Items: {totalItems}'),
  p('Low Stock Items: {lowStockItems}'),
  p('Total Value: {totalValue} units'),
  br(),
  p('ITEM DETAILS', true),
  br(),
  p('{#items}'),
  p('Item: {name}'),
  p('SKU: {sku}'),
  p('Category: {category}'),
  p('Quantity: {quantity} {unit}'),
  p('Min Stock Level: {minStockLevel}'),
  p('Status: {status}'),
  p('Description: {description}'),
  p('-------------------'),
  p('{/items}'),
].join('\n');

// Low Stock Alert Template
const lowStockAlertContent = [
  p('⚠ LOW STOCK ALERT', true),
  p('Alert Date: {reportDate}'),
  p('Generated By: {generatedBy}'),
  br(),
  p('ALERT SUMMARY', true),
  p('Total Low Stock Items: {alertCount}'),
  p('Critical (Out of Stock): {criticalItems}'),
  br(),
  p('ITEMS REQUIRING ATTENTION', true),
  br(),
  p('{#items}'),
  p('Item: {name}'),
  p('SKU: {sku}'),
  p('Category: {category}'),
  p('Current Quantity: {currentQuantity} {unit}'),
  p('Minimum Stock Level: {minStockLevel}'),
  p('Shortage: {shortage} units'),
  p('Status: {status}'),
  p('-------------------'),
  p('{/items}'),
].join('\n');

// Transaction Report Template
const transactionReportContent = [
  p('TRANSACTION REPORT', true),
  p('Report Date: {reportDate}'),
  p('Generated By: {generatedBy}'),
  p('Period: {startDate} to {endDate}'),
  br(),
  p('SUMMARY', true),
  p('Total Transactions: {totalTransactions}'),
  p('Total Stock In: {totalStockIn} units'),
  p('Total Stock Out: {totalStockOut} units'),
  p('Adjustments: {totalAdjustments}'),
  br(),
  p('TRANSACTION DETAILS', true),
  br(),
  p('{#transactions}'),
  p('Date: {date}'),
  p('Item: {item} (SKU: {sku})'),
  p('Type: {type}'),
  p('Quantity: {quantity}'),
  p('Reason: {reason}'),
  p('User: {user}'),
  p('-------------------'),
  p('{/transactions}'),
].join('\n');

// Item Label Template
const itemLabelContent = [
  p('═══════════════════════════════════'),
  p('ITEM LABEL', true),
  p('═══════════════════════════════════'),
  br(),
  p('{name}', true),
  br(),
  p('SKU: {sku}'),
  p('Category: {category}'),
  br(),
  p('Current Stock: {quantity} {unit}', true),
  br(),
  p('Description:'),
  p('{description}'),
  br(),
  p('Generated: {dateGenerated}'),
  p('═══════════════════════════════════'),
].join('\n');

// Create template files
const templates = [
  { name: 'inventory-report.docx', content: inventoryReportContent },
  { name: 'low-stock-alert.docx', content: lowStockAlertContent },
  { name: 'transaction-report.docx', content: transactionReportContent },
  { name: 'item-label.docx', content: itemLabelContent }
];

console.log('Creating Word template files...\n');

templates.forEach(({ name, content }) => {
  try {
    const buffer = createMinimalDocx(content);
    const filePath = path.join(__dirname, name);
    fs.writeFileSync(filePath, buffer);
    console.log(`✓ Created ${name}`);
  } catch (error) {
    console.error(`✗ Error creating ${name}:`, error.message);
  }
});

console.log('\n✓ Template creation complete!');
console.log('\nYou can now:');
console.log('1. Open these templates in Microsoft Word');
console.log('2. Customize the layout, fonts, colors, and formatting');
console.log('3. Keep the {placeholder} syntax intact');
console.log('4. Save the files when done\n');
