const officegen = require('officegen');
const fs = require('fs');
const path = require('path');

// Helper to create a document
const createDoc = () => {
  return officegen({
    type: 'docx',
    orientation: 'portrait',
    pageMargins: { top: 1000, right: 1000, bottom: 1000, left: 1000 }
  });
};

// Generate Inventory Report Template
const generateInventoryReportTemplate = () => {
  const docx = createDoc();
  
  let pObj = docx.createP({ align: 'center' });
  pObj.addText('INVENTORY REPORT', { bold: true, font_size: 18 });
  
  pObj = docx.createP();
  pObj.addText('Generated on: {reportDate}');
  
  pObj = docx.createP();
  pObj.addText('By: {generatedBy}');
  
  pObj = docx.createP();
  pObj.addLineBreak();
  
  pObj = docx.createP({ bold: true });
  pObj.addText('SUMMARY');
  
  pObj = docx.createP();
  pObj.addText('Total Items: {totalItems}');
  
  pObj = docx.createP();
  pObj.addText('Low Stock Items: {lowStockItems}');
  
  pObj = docx.createP();
  pObj.addText('Total Value: {totalValue} units');
  
  pObj = docx.createP();
  pObj.addLineBreak();
  
  pObj = docx.createP({ bold: true });
  pObj.addText('ITEM DETAILS');
  
  pObj = docx.createP();
  pObj.addLineBreak();
  
  // Table for items
  const table = [
    [{
      val: 'Item Name',
      opts: { b: true, color: '000000', fill: 'CCCCCC' }
    }, {
      val: 'SKU',
      opts: { b: true, color: '000000', fill: 'CCCCCC' }
    }, {
      val: 'Category',
      opts: { b: true, color: '000000', fill: 'CCCCCC' }
    }, {
      val: 'Quantity',
      opts: { b: true, color: '000000', fill: 'CCCCCC' }
    }, {
      val: 'Unit',
      opts: { b: true, color: '000000', fill: 'CCCCCC' }
    }, {
      val: 'Min Stock',
      opts: { b: true, color: '000000', fill: 'CCCCCC' }
    }, {
      val: 'Status',
      opts: { b: true, color: '000000', fill: 'CCCCCC' }
    }]
  ];
  
  docx.createTable(table);
  
  pObj = docx.createP();
  pObj.addText('{#items}');
  
  const itemTable = [
    ['{name}', '{sku}', '{category}', '{quantity}', '{unit}', '{minStockLevel}', '{status}']
  ];
  
  docx.createTable(itemTable);
  
  pObj = docx.createP();
  pObj.addText('{/items}');
  
  return docx;
};

// Generate Low Stock Alert Template
const generateLowStockAlertTemplate = () => {
  const docx = createDoc();
  
  let pObj = docx.createP({ align: 'center' });
  pObj.addText('LOW STOCK ALERT', { bold: true, font_size: 18, color: 'FF0000' });
  
  pObj = docx.createP();
  pObj.addText('Alert Date: {reportDate}');
  
  pObj = docx.createP();
  pObj.addText('Generated By: {generatedBy}');
  
  pObj = docx.createP();
  pObj.addLineBreak();
  
  pObj = docx.createP({ bold: true });
  pObj.addText('ALERT SUMMARY');
  
  pObj = docx.createP();
  pObj.addText('Total Low Stock Items: {alertCount}');
  
  pObj = docx.createP();
  pObj.addText('Critical (Out of Stock): {criticalItems}');
  
  pObj = docx.createP();
  pObj.addLineBreak();
  
  pObj = docx.createP({ bold: true });
  pObj.addText('ITEMS REQUIRING ATTENTION');
  
  pObj = docx.createP();
  pObj.addLineBreak();
  
  const table = [
    [{
      val: 'Item',
      opts: { b: true, color: '000000', fill: 'FFCCCC' }
    }, {
      val: 'SKU',
      opts: { b: true, color: '000000', fill: 'FFCCCC' }
    }, {
      val: 'Current',
      opts: { b: true, color: '000000', fill: 'FFCCCC' }
    }, {
      val: 'Min Level',
      opts: { b: true, color: '000000', fill: 'FFCCCC' }
    }, {
      val: 'Shortage',
      opts: { b: true, color: '000000', fill: 'FFCCCC' }
    }, {
      val: 'Status',
      opts: { b: true, color: '000000', fill: 'FFCCCC' }
    }]
  ];
  
  docx.createTable(table);
  
  pObj = docx.createP();
  pObj.addText('{#items}');
  
  const itemTable = [
    ['{name}', '{sku}', '{currentQuantity}', '{minStockLevel}', '{shortage}', '{status}']
  ];
  
  docx.createTable(itemTable);
  
  pObj = docx.createP();
  pObj.addText('{/items}');
  
  return docx;
};

// Generate Transaction Report Template
const generateTransactionReportTemplate = () => {
  const docx = createDoc();
  
  let pObj = docx.createP({ align: 'center' });
  pObj.addText('TRANSACTION REPORT', { bold: true, font_size: 18 });
  
  pObj = docx.createP();
  pObj.addText('Report Date: {reportDate}');
  
  pObj = docx.createP();
  pObj.addText('Generated By: {generatedBy}');
  
  pObj = docx.createP();
  pObj.addText('Period: {startDate} to {endDate}');
  
  pObj = docx.createP();
  pObj.addLineBreak();
  
  pObj = docx.createP({ bold: true });
  pObj.addText('SUMMARY');
  
  pObj = docx.createP();
  pObj.addText('Total Transactions: {totalTransactions}');
  
  pObj = docx.createP();
  pObj.addText('Total Stock In: {totalStockIn} units');
  
  pObj = docx.createP();
  pObj.addText('Total Stock Out: {totalStockOut} units');
  
  pObj = docx.createP();
  pObj.addText('Adjustments: {totalAdjustments}');
  
  pObj = docx.createP();
  pObj.addLineBreak();
  
  pObj = docx.createP({ bold: true });
  pObj.addText('TRANSACTION DETAILS');
  
  pObj = docx.createP();
  pObj.addLineBreak();
  
  const table = [
    [{
      val: 'Date',
      opts: { b: true, color: '000000', fill: 'CCCCCC' }
    }, {
      val: 'Item',
      opts: { b: true, color: '000000', fill: 'CCCCCC' }
    }, {
      val: 'Type',
      opts: { b: true, color: '000000', fill: 'CCCCCC' }
    }, {
      val: 'Quantity',
      opts: { b: true, color: '000000', fill: 'CCCCCC' }
    }, {
      val: 'Reason',
      opts: { b: true, color: '000000', fill: 'CCCCCC' }
    }, {
      val: 'User',
      opts: { b: true, color: '000000', fill: 'CCCCCC' }
    }]
  ];
  
  docx.createTable(table);
  
  pObj = docx.createP();
  pObj.addText('{#transactions}');
  
  const transTable = [
    ['{date}', '{item}', '{type}', '{quantity}', '{reason}', '{user}']
  ];
  
  docx.createTable(transTable);
  
  pObj = docx.createP();
  pObj.addText('{/transactions}');
  
  return docx;
};

// Generate Item Label Template
const generateItemLabelTemplate = () => {
  const docx = createDoc();
  
  let pObj = docx.createP({ align: 'center' });
  pObj.addText('ITEM LABEL', { bold: true, font_size: 16 });
  
  pObj = docx.createP();
  pObj.addLineBreak();
  
  pObj = docx.createP({ bold: true, font_size: 14 });
  pObj.addText('{name}');
  
  pObj = docx.createP();
  pObj.addLineBreak();
  
  pObj = docx.createP();
  pObj.addText('SKU: {sku}');
  
  pObj = docx.createP();
  pObj.addText('Category: {category}');
  
  pObj = docx.createP();
  pObj.addLineBreak();
  
  pObj = docx.createP({ bold: true });
  pObj.addText('Current Stock: {quantity} {unit}');
  
  pObj = docx.createP();
  pObj.addLineBreak();
  
  pObj = docx.createP();
  pObj.addText('Description:');
  
  pObj = docx.createP();
  pObj.addText('{description}');
  
  pObj = docx.createP();
  pObj.addLineBreak();
  
  pObj = docx.createP({ font_size: 8 });
  pObj.addText('Generated: {dateGenerated}');
  
  return docx;
};

// Save all templates
const templates = [
  { name: 'inventory-report', generator: generateInventoryReportTemplate },
  { name: 'low-stock-alert', generator: generateLowStockAlertTemplate },
  { name: 'transaction-report', generator: generateTransactionReportTemplate },
  { name: 'item-label', generator: generateItemLabelTemplate }
];

console.log('Generating template files...\n');

templates.forEach(({ name, generator }) => {
  const docx = generator();
  const outputPath = path.join(__dirname, `${name}.docx`);
  
  const out = fs.createWriteStream(outputPath);
  
  out.on('error', (err) => {
    console.error(`Error creating ${name}.docx:`, err);
  });
  
  docx.on('finalize', () => {
    console.log(`✓ Created ${name}.docx`);
  });
  
  docx.on('error', (err) => {
    console.error(`Error generating ${name}.docx:`, err);
  });
  
  docx.generate(out);
});

console.log('\nNote: The generated templates contain placeholder text.');
console.log('You can open them in Microsoft Word and customize the layout, fonts, colors, etc.');
console.log('Make sure to keep the placeholder syntax {variableName} intact.\n');
